language: c

dist: trusty

before_install: ci/install-dependencies.sh

script: ci/run-build-and-tests.sh

sudo: required

git:
  depth: 2147483647

env:
  global:
    - SLEEP_A_BIT="sleep 0.2"
    - VERBOSE="1"

matrix:
  include:
    - compiler: gcc
      env:
        - TARGET=x86_64
        - STACKTRACE=libunwind
        - CHECK=coverage
        - KHEADERS=torvalds/linux
    - compiler: gcc
      env:
        - TARGET=x86_64
        - STACKTRACE=libunwind
    - compiler: gcc
      env:
        - TARGET=x32
        - STACKTRACE=no
    - compiler: gcc
      env:
        - TARGET=x86
        - STACKTRACE=no
    - compiler: clang
      env:
        - TARGET=x86_64
        - STACKTRACE=libunwind
    - compiler: musl-gcc
      env:
        - TARGET=x86_64
        - STACKTRACE=no
    - compiler: clang
      env:
        - TARGET=x86
        - STACKTRACE=no
    - compiler: musl-gcc
      env:
        - TARGET=x86
        - STACKTRACE=no
    - compiler: gcc-7
      env:
        - TARGET=x86_64
        - STACKTRACE=libunwind
    - compiler: gcc-7
      env:
        - TARGET=x32
        - STACKTRACE=no
    - compiler: gcc-7
      env:
        - TARGET=x86
        - STACKTRACE=no
    - compiler: gcc
      env:
        - TARGET=x86_64
        - STACKTRACE=no
