language: c

dist: trusty

before_install: ci/install-dependencies.sh

script: travis_wait 60 ci/run-build-and-tests.sh

sudo: required

git:
  depth: 2147483647

env:
  global:
    - SLEEP_A_BIT="sleep 0.2"
    - VERBOSE="1"

matrix:
  include:
    - compiler: gcc
      env:
        - TARGET=x86_64
        - STACKTRACE=libunwind
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=memcheck
        - VALGRIND_TESTDIR=tests
        - VALGRIND_TESTS=looping_threads.test
