language: c

dist: bionic

before_install: ci/install-dependencies.sh

script: travis_wait 40 ci/run-build-and-tests.sh

sudo: required

git:
  depth: 2147483647

env:
  global:
    - KHEADERS=""
    - SLEEP_A_BIT="sleep 0.2"
    - STACKTRACE=""
    - TARGET=""
    - TIMEOUT_DURATION=""
    - VERBOSE="1"

matrix:
  include:
    - compiler: gcc
      arch: amd64
      env:
        - TARGET=x86
        - STACKTRACE=no
    - compiler: musl-gcc
      arch: amd64
      dist: trusty
      env:
        - TARGET=x86
        - STACKTRACE=no
    - compiler: gcc
      arch: arm64
      env:
        - TARGET=aarch64
        - SLEEP_A_BIT="sleep 0.5"
        - STACKTRACE=no
    - compiler: gcc
      arch: arm64
      env:
        - TARGET=aarch64
        - SLEEP_A_BIT="sleep 0.5"
        - STACKTRACE=no
        - KHEADERS=torvalds/linux
    - compiler: clang-9
      arch: arm64
      env:
        - TARGET=aarch64
        - SLEEP_A_BIT="sleep 0.5"
        - STACKTRACE=no
    - compiler: gcc
      arch: ppc64le
      env:
        - TARGET=ppc64le
        - STACKTRACE=libdw
    - compiler: gcc
      arch: s390x
      env:
        - TARGET=s390x
        - STACKTRACE=libdw
    - compiler: gcc-10
      arch: ppc64le
      env:
        - TARGET=ppc64le
        - STACKTRACE=no
        - KHEADERS=torvalds/linux
    - compiler: gcc-10
      arch: s390x
      env:
        - TARGET=s390x
        - STACKTRACE=no
        - KHEADERS=torvalds/linux
