language: c

dist: trusty

before_install: ./travis-install.sh

script: ./travis-build.sh

sudo: required

git:
  depth: 2147483647

env:
  global:
    - SLEEP_A_BIT="sleep 0.2"
    - VERBOSE="1"

matrix:
  include:
    - compiler: gcc
      env:
        - TARGET=x86_64
    - compiler: gcc
      env:
        - TARGET=x32
    - compiler: gcc
      env:
        - TARGET=x86
    - compiler: clang-3.8
      env:
        - TARGET=x86_64
    - compiler: musl-gcc
      env:
        - TARGET=x86_64
    - compiler: clang-3.8
      env:
        - TARGET=x86
    - compiler: musl-gcc
      env:
        - TARGET=x86
    - compiler: gcc-6
      env:
        - TARGET=x86_64
    - compiler: gcc-6
      env:
        - TARGET=x32
    - compiler: gcc-6
      env:
        - TARGET=x86
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=coverage
        - KHEADERS=torvalds/linux
